version: "2"
services:
  redis:
    image: redis
    ports: 
        - 6379:6379
    command: redis-server --requirepass lala2020 
  mongo:
    image: mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=lala2020
      - MONGO_INITDB_DATABASE=admin
    ports:
      - 27017:27017
    volumes:
      - ./mongo_volume:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: mongod