version: "2"
services:
  mycrawler:
    build: ./
    environment:
      REDIS_HOST: redis
      REDIS_PASSWORD: "lala2020"
      MONGODB_SERVER: mongo
      MONGODB_DB: "debug"
      MONGODB_DATA_COLLECTION: "debug"
      MONGODB_USER: "root"
      MONGODB_PASSWORD: "lala2020"
      SQLDB_SERVER: "10.150.80.5"
      SQLDB_USERNAME: "news_agent"
      SQLDB_PASSWORD: "News@1313"
      SQLDB_DB: "news-v1"
      SQLDB_DATA_TABLE: "myyl_raw"
    links:
      - redis
      - mongo
    volumes:
      - ./mycrawler_log:/app/log
  redis:
    image: redis
    ports: 
        - 6379:6379
    command: redis-server --requirepass lala2020 
  mongo:
    image: mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=lala2020
      - MONGO_INITDB_DATABASE=admin
    ports:
      - 27017:27017
    volumes:
      - ./mongo_volume:/data/db
    command: mongod